export const customersDetails = [
	{
		id: 1,
		name: 'Hari Kumar',
		project: '	Product Devlopment',
		task: 'UI finished',
		hours: '3',
		document: 'view',
		createdBy: 'Ramkumar',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Admin',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 2,
		name: 'Surya',
		project: '	Product Devlopment',
		task: 'Backend finished',
		hours: '6',
		createdBy: 'Ramkumar',
		document: 'view',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 3,
		name: 'Ravi',
		project: 'New Office Building',
		task: 'UI error fixed',
		hours: '7',
		createdBy: 'kumar',
		document: 'view',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Admin',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 4,
		name: 'Anand',
		project: 'New Office Building',
		task: 'Api error fixed for login',
		hours: '1',
		document: 'view',
		createdBy: 'Ramkumar',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 5,
		name: 'Praveen',
		project: 'Website & Blog',
		task: 'session error fixed',
		hours: '4',
		createdBy: 'Ramkumar',
		document: 'view',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 6,
		name: 'Ravi',
		task: 'Udhaya',
		project: 'Website & Blog',
		hours: '5',
		createdBy: 'Ramkumar',
		document: 'view',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 7,
		name: 'Ravi',
		task: 'kumar',
		project: 'Export Marketing',
		hours: '5',
		createdBy: 'Ramkumar',
		document: 'view',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 8,
		name: 'Ravi',
		task: 'Siva',
		project: 'Export Marketing',
		hours: '2',
		createdBy: 'Ramkumar',
		document: 'view',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
]
