import { date } from "yup";

export const customersDetails = [
	{
		id: 1,
		name: 'Hari Kumar',
		project: '	Product Devlopment',
		date: '01-Oct-2025',
		task: 'UI finished',
		hours: '3',
		document: 'view',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Admin',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 2,
		name: 'Surya',
		project: 'Product Devlopment',
		date: '01-Jun-2025',
		task: 'Backend finished',
		hours: '6',
		document: 'view',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 3,
		name: 'Ravi',
		project: 'New Office Building',
		date: '11-Mar-2025',
		task: 'UI error fixed',
		hours: '7',
		document: 'view',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Admin',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 4,
		name: 'Anand',
		project: 'New Office Building',
		date: '01-Jan-2025',
		task: 'Api error fixed for login',
		hours: '1',
		document: 'view',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 5,
		name: 'Praveen',
		project: 'Website & Blog',
		date: '02-Jun-2024',
		task: 'session error fixed',
		hours: '4',
		document: 'view',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 6,
		name: 'Ravi',
		task: 'Cookkies handle cjecked',
		date: '02-Jul-2024',
		project: 'Website & Blog',
		hours: '5',
		document: 'view',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 7,
		name: 'Ravi',
		task: 'DB error fixed',
		project: 'Export Marketing',
		date: '02-Nov-2024',
		hours: '5',
		document: 'view',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 8,
		name: 'Ravi',
		task: 'Schema design finished ',
		project: 'Export Marketing',
		date: '01-Dec-2024',
		hours: '2',
		document: 'view',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
]
