export const customersDetails = [
	{
		id: 1,
		name: 'Unity Pugh',
		ext: 'unity@gmail.com',
		city: 'Admin',
		startDate: 'Elliott Snyder',
		completion: '37%',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Admin',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 2,
		name: 'Theodore Duran',
		ext: 'bruno@gmail.com',
		city: 'Employee',
		startDate: 'Elliott Snyder',
		completion: '97%',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 3,
		name: 'Kylie Bishop',
		ext: 'kylie@gmail.com',
		city: 'Employee',
		startDate: 'Elliott Snyder',
		completion: '63%',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Admin',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 4,
		name: 'Willow Gilliam',
		ext: 'ges@gmail.com',
		city: 'HR',
		startDate: 'Unity Pugh',
		completion: '30%',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 5,
		name: 'Blossom Dickerson',
		ext: 'hari@gmail.com',
		city: 'Employee',
		startDate: 'Unity Pugh',
		completion: '17%',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 6,
		name: 'Elliott Snyder',
		ext: 'syn@gmail.com',
		city: 'Admin',
		startDate: 'Unity Pugh',
		completion: '57%',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 7,
		name: 'Castor Pugh',
		ext: 'pugh@gmail.com',
		city: 'Employee',
		startDate: 'Unity Pugh',
		completion: '93%',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 8,
		name: 'Pearl Carlson',
		ext: 'peal@gmail.com',
		city: 'Employee',
		startDate: 'Unity Pugh',
		completion: '100%',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 9,
		name: 'Deirdre Bridges',
		ext: 'ridges@gmail.com',
		city: 'Employee',
		startDate: 'Unity Pugh',
		completion: '44%',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 10,
		name: 'Daniel Baldwin',
		ext: 'rid@gmail.com',
		city: 'Employee',
		startDate: 'Unity Pugh',
		completion: '33%',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 11,
		name: 'Pearl Carlson',
		ext: 'car6231@gmail.com',
		city: 'Employee',
		startDate: 'Unity Pugh',
		completion: '100%',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
]
