export const customersDetails = [
	{
		id: 1,
		name: 'Product Devlopment',
		manager: 'Ramkumar',
		client: 'Hariram',
		employee: 'siva, ram, dinesh',
		startDate: '20/Jan/2024',
		endDate: '02/Mar/2024',
		status: 'Active',
		createdBy: 'Ramkumar',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Admin',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 2,
		name: 'New Office Building',
		manager: 'Brun',
		client: 'Ganesh',
		employee: 'siva, karthick',
		startDate: '02/Apr/2025',
		endDate: '02/Nov/2025',
		status: 'Pending',
		createdBy: 'Ramkumar',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 3,
		name: 'Website & Blog',
		manager: 'Kylie',
		client: 'karthi',
		employee: 'mohan',
		startDate: '20/Dec/2024',
		endDate: '02/Mar/2025',
		status: 'Completed',
		createdBy: 'kumar',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Admin',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 4,
		name: 'Market Research',
		manager: 'Ges',
		client: 'Dinesh',
		employee: 'Akash',
		startDate: '20/Oct/2025',
		endDate: '02/Aug/2025',
		status: 'Pending',
		createdBy: 'Ramkumar',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 5,
		name: 'Export Marketing	',
		manager: 'Hari',
		client: 'Siva kumar',
		employee: 'dinesh',
		startDate: '12/May/2025',
		endDate: '02/Jun/2025',
		status: 'Not Started',
		createdBy: 'Ramkumar',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 6,
		name: 'Website & Blog',
		client: 'Udhaya',
		manager: 'Syn',
		employee: 'udhaya',
		startDate: '02/Nov/2024',
		endDate: '02/Feb/2025',
		createdBy: 'Ramkumar',
		status: 'Active',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 7,
		name: 'Castor Pugh',
		client: 'kumar',
		manager: 'Pugh',
		employee: 'ravi',
		startDate: '02/Jun/2024',
		endDate: '02/Aug/2025',
		createdBy: 'Ramkumar',
		status: 'Active',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
	{
		id: 8,
		name: 'Pearl Carlson',
		client: 'Siva',
		manager: 'Peal',
		employee: 'prasanth',
		startDate: '02/Mar/2024',
		endDate: '02/Jun/2025',
		createdBy: 'Ramkumar',
		status: 'Active',
		subRows: [
			{
				id: 51,
				age: 23,
				name: 'Bruno',
				company: 'Magmina',
				phone: '+1 (813) 583-2089',
			},
		],
	},
]
